import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>拍照即賣、私訊即買，免費拍賣平台就在Carousell旋轉拍賣！</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <div className=' bg-neutral-800 py-2 lg:px-24'>
        
        <a className='text-white text-sm '>Cars & Property</a>
        <a className='text-white text-sm ml-4'>Fashion</a>
        <a className='text-white text-sm ml-4'>Home & Living</a>
        <a className='text-white text-sm ml-4'>Mobiles & Electronics</a>
        <a className='text-white text-sm ml-4'>Hobbies & Games</a>
        <a className='text-white text-sm ml-4'>Jobs & Services</a>
        <a className='text-white text-sm ml-4'>Others</a>
        <a className='text-white text-sm ml-96 font-semibold'>Register</a>
        <a className='text-white text-sm ml-6 font-semibold'>Login</a>
        </div>
       
      </main>

      
    </div>
  )
}
