import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>拍照即賣、私訊即買，免費拍賣平台就在Carousell旋轉拍賣！</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Carousell-logo-square.ico" />
      </Head>

      <main className=''>

        {/*content bar start*/}
        <div className='bg-neutral-800 py-2 px-14 flex items-center'>

          <img src = "/white Carousell-logo-square.png" width={33} height={33} />
          <p className=' text-white text-opacity-30 ml-2.5 text-xl font-extralight'>|</p>    
          <a className='text-white text-sm ml-3'>Cars & Property</a>
          <a className='text-white text-sm ml-6'>Fashion</a>
          <a className='text-white text-sm ml-6'>Home & Living</a>
          <a className='text-white text-sm ml-6'>Mobiles & Electronics</a>
          <a className='text-white text-sm ml-6'>Hobbies & Games</a>
          <a className='text-white text-sm ml-6'>Jobs & Services</a>
          <a className='text-white text-sm ml-6'>Others</a>
          <a className='text-white text-sm ml-auto font-semibold'>Register</a>
          <a className='text-white text-sm ml-6 font-semibold pr-9'>Login</a>
        </div>
        {/*content bar end*/}

        {/*search bar start*/}
       <div className=' items-center flex px-16 py-2 border-b-neutral-100 border-b'>
          <img src="/carousell-logo.svg" width={168} height={32}/>
          <input className=' bg-gray-100 h-12 w-391 ml-6 px-4 rounded-l focus:outline-none focus:ring-4 focus:ring-teal-600/20 focus:ring-offset-1 focus:ring-offset-teal-600 focus:bg-white' placeHolder="Search for an item" spellCheck='false' type='text'></input>
          <div>
            <input className=' bg-gray-100 h-12 w-274 ml-0.25 px-12 focus:outline-none focus:ring-4 focus:ring-teal-600/20 focus:ring-offset-1 focus:ring-offset-teal-600 focus:bg-white' placeHolder="All of Hong Kong" spellCheck='false' type='text' list='venue'></input>
            <datalist id='venue'>
              <option value='Listing near me'/>
              <option value='All of Hong Kong'/>
              <option value='Area'/>
              <option value='District'/>
              <option value='MTR'/>
            </datalist>
          </div>
          <div className='rounded-r w-58 flex h-12 bg-gray-100 justify-center'>
            <button className='place-self-center h-8 w-10 pl-3 bg-teal-600  rounded-sm' role="submitButton" type="submit">
              <img className='h-4 w-4' src='/search-line-3.png'></img>
            </button>
          </div>
          <div className='pl-304px '>
            <button className='w-76px  h-8 rounded-md text-white font-medium bg-red-500 active:bg-red-700 '>Sell</button>
          </div>
       </div>
        {/*Search bar end*/}

        {/*Feature start*/}
        <div className='flex justify-center py-4 gap-4 mr-6'>
          <a>
            <img src='/13782050885610001892.jpeg' width={648} height={264}></img>
          </a>
          <a>
            <img src='Cleaning_services_CNY_App_(1500,_610).png.jpeg' width={648} height={264}></img>
          </a>
          <button className='-ml-10'>
            <img className='w-10 h-10 opacity-80 drop-shadow-4xl' src='/Asset 2.png'></img>
          </button>
        </div>
        {/*Featyure end*/}
        {/*Explore Carousell start*/}
        <p className='pl-16 text-2xl font-medium pt-10'>Explore Carousell</p>
        <div className='pl-16 pt-8 flex'>
          <div className='w-121px h-152px'>
            <a className=''>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/56-Following-cxxhdpi_1579665374.01.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pl-3 pt-2'>Following</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/56-Services-cxxhdpi_1579665464.54.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pl-5 pt-2'>Services</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/01_computers_tech.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-8 pt-3 text-center'>Computers & Tech</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/02_mobile_phones_gadgets.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-6 pt-3 text-center'>Mobile Phones & Gadgets</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/08_womens_fashion.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-8 pt-3 text-center'>Women's Fashion</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/56-Property-cxxhdpi_1579665459.19.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-8 pt-3 text-center'>Property</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/09_mens_fashion.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-7 pt-3 text-center'>Men's Fashion</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/56-Cars-cxxhdpi_1579665347.31.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-9 pt-3 text-center'>Cars</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/13_beauty_personal_care.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-6 pt-3 text-center'>Beauty & Per-sonal Care</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/10_luxury.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-8 pt-3 text-center'>Luxury</p>
            </a>
          </div>
          <div className='w-121px h-152px'>
            <a className='pl-1'>
              <div className='rounded-full w-86px h-86px transition ease-in-out duration-300 hover:bg-gray-200/70 hover:-translate-y-1 inline-flex justify-center'>
                <img src='/freeitems-1579255406.png' className='w-72px h-72px place-self-center'/>
              </div>
              <p className='text-sm text-black/70 pr-7 pt-3 text-center'>Free Items</p>
            </a>
          </div>
          <button className='-ml-86px'>
            <img className='w-10 h-10 opacity-80 drop-shadow-4xl' src='/Asset 2.png'></img>
          </button>
        </div>
        {/*Explore Carousell end*/}

        {/*Recommended For you start*/}
        <p className='pl-16 text-2xl font-medium pt-10'>Recommended For you</p>
        <div>

        </div>
        {/*Recommended For you end*/}
      </main>
      
      
    </div>
  )
}
